[env:lolin_s3_mini]
platform = espressif32@^6.7.0
board = lolin_s3_mini
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = huge_app.csv

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    esphome/ESPAsyncWebServer-esphome @ ^3.1.0
    bblanchon/ArduinoJson @ ^6.21.3
    robtillaart/PCF8574 @ ^0.3.8
    https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.12
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit SH110X @ ^2.1.8
    adafruit/Adafruit GFX Library @ ^1.11.9
