[env:esp32dev]
platform = espressif32@^6.7.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = huge_app.csv

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D AUDIOKIT_BOARD=5

lib_deps =
    esphome/ESPAsyncWebServer-esphome @ ^3.1.0
    bblanchon/ArduinoJson @ ^6.21.3
    olikraus/U8g2 @ ^2.34.22
    https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.12
    https://github.com/pschatzmann/arduino-audiokit.git
